=== AparnaBalel/Gadgets-Repairing-Service/src/main/resources/company.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="technicianType">
        <xs:sequence>
            <xs:element name="technicianID" type="xs:long" minOccurs="0"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="Email" type="xs:string"/>
            <xs:element name="Phone" type="xs:long"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>
    <xs:complexType name="techniciansType">
        <xs:sequence>
            <xs:element name="technician" type="technicianType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="companyType">
    <xs:sequence>
        <xs:element name="technicians" type="techniciansType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    </xs:complexType>
    <xs:element name="company" type="companyType" />
</xs:schema>

=== AparnaBalel/Gadgets-Repairing-Service/src/main/resources/company.xml
<company xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "company.xsd">
    <technicians>
        <technician id="1">
            <technicianID> 1 </technicianID>
            <firstName> Joan </firstName>
            <lastName> Allen </lastName>
            <Email> Joan_Allen@email.com </Email>
            <Phone> 1987654321 </Phone>
        </technician>
        <technician id="2">
            <technicianID> 2 </technicianID>
            <firstName> Joana </firstName>
            <lastName> Albert </lastName>
            <Email> J_Albert@email.com </Email>
            <Phone> 1234567891 </Phone>
        </technician>
    </technicians>
</company>
